name: Coverage

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/tarpaulin@v0.1
      - uses: codecov/codecov-action@v3
        # A codecov token is not needed for public repos if the repo is linked
        # on codecov.io. See https://docs.codecov.com/docs/frequently-asked-questions#where-is-the-repository-upload-token-found
      - uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml
